version: '2'
services:
  frontend:
    build: frontend
    ports:
    - "8080:8080"
    depends_on:
    - backend
    environment:
    - PORT=8080
    - NODE_ENV=production
    - BACKEND_URL=http://backend:3000/
  backend:
    build: backend
    ports:
    - "3000:3000"
    depends_on:
    - mongodb
    environment:
    - PORT=3000
    - NODE_ENV=production
    - MONGODB_URL=mongodb://mongodb:27017
  mongodb:
    image: mongo:3.2
    ports:
     - "27017:27017"
