apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: pdressel/devcon:backend
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URL
          value: mongodb://mongodb-0.mongodb:27017
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3000"
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
